sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
language: python
python:
- '3.4'
- '3.6'
env:
- DRIVER=pymongo
- DRIVER=motor
- DRIVER=txmongo
before_install:
- mongo --version
- pip install -U six
install:
- pip install -U tox
- pip install -U coveralls
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION-$DRIVER | tr -d .) -- -v
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: touilleMan
  password:
    secure: cQN5qW1k5kMQprmgIWiqjXyvH5SdZCs93a1f5NVquo/NsxFvwvtm6J3Zmp8NaC4tvRzSpyolZyW+5o0ISXBMiLPpv4cqGHdSaKfzWRWtTUy+JdQjcZxcPi7vD7E+HJha1+7gjpoX8qXD8NyOlWr4VFhQxWd77cFA19tgIvhbDCMN1BadaCObNDI/D8jomVygGH/G5bk4QQc9+xl7JSbBzGcncEjUXa83WSFgXXuQtnFchArR12YQQSVN4Y1Rnm215haatJ511oGEby3PAkUw4kaScbW/lo8w2hAY/p9YRAV9+5SXASDCdta53opawoX9rFfGCiZhuil5XJCxz29IqLD5TtcWOyzte45Soz7VYf7wWdmokMCxZO3lMv6IH275VdZOYrDRrRAM9pO0HxPF5K6hZxi4tZgSsFgdV9t4qfjpQp0cazseCpiCSRtWbNWYXkrdm+LWnbIkC1Oz2np4Ehw+rEpRHZyd31ENyhKhG1n6GNuZrtTjIeRYnTolV5mOudZqvib8egqtck4ehWrA4rgJtYwzoLKEI2OtRYxjLaLrOKYn5rGrDM1ayeFQA13NCJ5LqCv6qFtswYVA96bKbB66HAygySeQZr/lYlgzAbmLi/bVV7JO+auG79RWyyr3n0Yz9rmovNuWEBCbAei3ghL8sRx2a9ifEveXVh3ZK0U=
  on:
    tags: true
    repo: Scille/umongo
    python: 3.6
  skip_existing: true
