trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

stages:
  - stage: lint
    jobs:
      - template: job--python-tox.yml@sloria
        parameters:
          toxenvs: [lint]
          coverage: false
  - stage: test
    jobs:
      - template: job--python-tox.yml@sloria
        parameters:
          toxenvs:
            - py37-pymongo
            - py37-motor1
            - py37-txmongo
            - py38-pymongo
            - py38-motor2
            - py38-txmongo
          coverage: true
          pre_test:
              - script: mongod --version
              - script: sudo systemctl start mongod
  - stage: release
    jobs:
      - template: job--pypi-release.yml@sloria
